### ISSUE TITLE
VaultChangeWatcher and multiple VaultConfiguration Providers

### ISSUE THREAD

**Issue by almostjulian** [MrZoidberg/VaultSharp.Extensions.Configuration#12]
Could VaultChangeWatcher be changed to handle multiple Vault Configuration Providers?  I find sometimes I have to create multiple because certain secrets are in different paths.

**Comment by MrZoidberg** [comment]
@almostjulian Hi, it's a good idea and I can check it on the weekend. Thanks!

**Comment by MrZoidberg** [comment]
@almostjulian please check #13 if this is what you need?

**Comment by almostjulian** [comment]
Looks good to me.... thanks!

**Comment by MrZoidberg** [comment]
Released.
