### ISSUE TITLE
Make code analyzers private

### ISSUE THREAD

**Issue by redwyre** [MrZoidberg/VaultSharp.Extensions.Configuration#16]
The way `Microsoft.VisualStudio.Threading` is currently referenced means anyone referencing this package will get the included analyzers if they want them or not. As a number of them are related to the use of their package it doesn't make sense to force them on users of your package.

I think this can be fixed by changing
```
<PackageReference Include="Microsoft.VisualStudio.Threading" Version="16.6.13" />
```
to
```
<PackageReference Include="Microsoft.VisualStudio.Threading" Version="16.6.13" >
  <PrivateAssets>analyzers</PrivateAssets>
</PackageReference>
```

**Comment by MrZoidberg** [comment]
@redwyre nice spot! feel free to do a PR or I can fix this on a weekend.

**Comment by redwyre** [comment]
I looked into this a bit further and it looks like there's actually a bug with nuget/dotnet where excluding analyzers is ignored: https://github.com/dotnet/sdk/issues/1212

Currently the only way to resolve it is to use `<PrivateAssets>all</PrivateAssets>`

**Comment by MrZoidberg** [comment]
@redwyre Actually Microsoft.VisualStudio.Threading is used in the code and can't be private. Please reopen the issue if there are any related problems. Also see #19
