### ISSUE TITLE
Update to 0.4.0 leads to System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by DsAekb** [MrZoidberg/VaultSharp.Extensions.Configuration#19]
### Describe the bug

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'Microsoft.VisualStudio.Threading, Version=16.10.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VaultSharp.Extensions.Configuration.VaultConfigurationProvider.Load()

### To Reproduce

Update nuget package version from 0.3.3 to 0.4.0

### Expected behaviour

No exceptions.

**Comment by MrZoidberg** [comment]
Thanks for raising. Will check out

**Comment by MrZoidberg** [comment]
Fixed in 0.4.1
