### ISSUE TITLE
Ability to configure namespace on this extension

### ISSUE THREAD

**Issue by mc-acc** [MrZoidberg/VaultSharp.Extensions.Configuration#21]
@MrZoidberg, I would like to have the ability to configure namespace for this extension, I have submitted the following pr #20

**Comment by MrZoidberg** [comment]
@mc-acc thanks a lot for your contribution. please check my comment there

**Comment by mc-acc** [comment]
Yes, the integration tests have a dependency on Docker-testcontainers which does not seem to work with my work pc that has a docker installation on wsl2 (because of the new licensing).  But, they do run on my home pc that uses docker desktop so I can work on that tonight.

**Comment by MrZoidberg** [comment]
@mc-acc Check out https://github.com/containers/podman. It's like Docker, but free. You can also alias docker to podman, so it will be transparent for other apps
