### ISSUE TITLE
How to Add VaultChangeWatcher

### ISSUE THREAD

**Issue by MaximTs** [MrZoidberg/VaultSharp.Extensions.Configuration#23]
### Question

Hi!
I've tried to call:

`services.AddHostedService<VaultChangeWatcher>();`

and get this error on runtime after `CreateHostBuilder(args).Build().Run();`:
`Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: VaultSharp.Extensions.Configuration.VaultChangeWatcher': Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfigurationRoot' while attempting to activate 'VaultSharp.Extensions.Configuration.VaultChangeWatcher'.)`

Can yo tell me what I'm doing wrong, please?

**Comment by MrZoidberg** [comment]
@MaximTs thanks for pointing out. I'll check this during the weekend. Quite a busy during war time. Sorry.

**Comment by MaximTs** [comment]
@MrZoidberg I understand. Same situation.
If it's possible, maybe it's worth getting rid of the `VaultChangeWatcher`?
Like just `AddConsul()` from `VaultSharp.Extensions.Configuration` and nothing else.
Thanks for replying.

**Comment by MrZoidberg** [comment]
@MaximTs sorry for the late reply. I've fixed this problem with `IConfigurationRoot` in the .NET 6 brach and it will be merged soon. It will be a multi-target lib with .netstandard 2.1 and .NET 6 support.

**Comment by MaximTs** [comment]
Good evening!
I added login/password integration to your lib and improve autoreading 
configs (without redundant extension)
If you interested in, I could create merge request.

**Comment by MrZoidberg** [comment]
Sure!

**Comment by MaximTs** [comment]
День добрый.
Прошу прощения, но у меня не получилось создать pull request.
Я создал develop-ветку и от нее feature/removeWatcher.
Попытался запушить, но тщетно из-за отсутствия прав.
Добавил во вложении zip с данной веткой проекта.

Некоторые тесты пришлось выключить из-за Watcher'а и упрощенного конструктора для options.
Привел код к требованиям editorconfig'а.
Поправил sample с новым конструктором.

Ветку брал с коммита за 17.05.2022.

Сорри за задержку, только появилось время переписать.

***@***.***

**Comment by MrZoidberg** [comment]
Please feel free to re-open this ticket if you have any additional questions.
