### ISSUE TITLE
Expand sample with IOptionsMonitor/Snapshot support

### ISSUE THREAD

**Issue by Reintjuu** [MrZoidberg/VaultSharp.Extensions.Configuration#26]
I noticed you've started working on the .NET6 migration a few days ago, I hope the PR will be merged soon.

I tried to expand on your integration tests and README by integrating the IOptionsMonitor in a project, but I don't quite understand how. Could you expand your sample project in this repo by including the IOptions reload support?

**Comment by MrZoidberg** [comment]
Hi, I also hope to finish this update in the nearest few days.
In the .NET 6 branch, I've included the `HelloController`with example of how to use `IOptionsSnapshot`. You can try to start this example in docker or outside and change the setting in Vault and the controller action will return a new value in a while.

**Comment by Reintjuu** [comment]
Looks great, thanks. I've managed to create a working solution with your example. There is one more issue with the IOptionsMonitor always triggering OnChange, but I'll create another issue for that on GitHub tomorrow.
