### ISSUE TITLE
Exception - "permission denied" to Execute ReadSecretPathsAsync

### ISSUE THREAD

**Issue by k0st1x** [MrZoidberg/VaultSharp.Extensions.Configuration#31]
I have an AppRole with restrictions, so It cannot view the metadata with kv list.
But I know the specific KV-names to read for the app.
Is it possible to specify multiple KV paths?
Or maybe is it possible to disable the executing "ReadSecretPaths" because of restricted permissions for "v1/\<engine\>/metadata/\<name\>" url access?

**Comment by MrZoidberg** [comment]
@k0st1x Hmm, interesting issue. So you can't read metadata and you want to specify all paths to read, right?

**Comment by MrZoidberg** [comment]
Do you have an example of your AppRole Vault configuration that I can use in tests?

**Comment by MrZoidberg** [comment]
@k0st1x Please take a look at https://github.com/MrZoidberg/VaultSharp.Extensions.Configuration/pull/32/files#diff-d1945bc4a9493a907abccce6f70d85d099e3ff4177049c7e2fa48a5969671e34 `Success_AppRoleAuthMethodNoListPermissions` test.

I've used the following permissions:
```
path "secret/*" {
  capabilities = [ "read" ]
}
```

To make it work I've introduced `AlwaysAddTrailingSlashToBasePath` option that is set to false when you don't have permission to list keys. The downside is that the base path should point to the key with JSON value, not the "folder".

I hope this works for you. Looking forward to your feedback and I'll release a new major version afterward.

**Comment by k0st1x** [comment]
Currently, devops regenerate approle permissions with metadata access, so current issue is irrelevant for me.
@MrZoidberg thank you for your activity, time, and for your current package.

**Comment by MrZoidberg** [comment]
@k0st1x cool. just a note that version 6.0.2 is out that doesn't use `ReadSecretPaths` with `AlwaysAddTrailingSlashToBasePath = false`

**Comment by k0st1x** [comment]
@MrZoidberg, I've just tried updated your package and it works without issue. thx.
