### ISSUE TITLE
Please add support to .netstandard2.0

### ISSUE THREAD

**Issue by oyetteramirez** [MrZoidberg/VaultSharp.Extensions.Configuration#37]
We would like to use this nuget package for a package that is on .netstandard2.0. We are not ready to move that package to netstandard2.1.

It looks like not a lot of changes are necessary. Ranges are not supported in netstandard2.0, so this line would need to be updated to Substring: https://github.com/MrZoidberg/VaultSharp.Extensions.Configuration/blob/master/Source/VaultSharp.Extensions.Configuration/VaultConfigurationProvider.cs#L106

**Comment by MrZoidberg** [comment]
Sure, will do this in the nearest days.

**Comment by MrZoidberg** [comment]
Done in 0.6.3
