### ISSUE TITLE
Add automatic login token refresh

### ISSUE THREAD

**Issue by CodeLover254** [MrZoidberg/VaultSharp.Extensions.Configuration#43]
VaultSharp documentation indicates there is no support for automatic token refresh but the host apps can do it by calling vaultClient.V1.Auth.ResetVaultToken() method. Is there a way to have the vaultClient property accessible so one can call the method at will?

**Comment by MrZoidberg** [comment]
Hi @CodeLover254!  I made a prototype https://github.com/MrZoidberg/VaultSharp.Extensions.Configuration/pull/44. I don't have time at the moment to do proper testing, but if you can test locally I can release it and write some tests later on. Any help is highly appreciated.

Thank you!

**Comment by CodeLover254** [comment]
Hi @MrZoidberg. I will have it tested and provide feedback. Thank you for your time.

**Comment by CodeLover254** [comment]
Hello @MrZoidberg , I performed a manual test and utilised token self lookup to ensure a new one had been issued and it worked as expected.

<img width="863" alt="Screenshot 2023-10-25 at 14 46 32" src="https://github.com/MrZoidberg/VaultSharp.Extensions.Configuration/assets/15217384/be2d1bb4-4ba2-4ae6-a80f-bf4546fa045b">

**Comment by CodeLover254** [comment]
The cref in the code comment is causing build fails though. Had to change it to href.

**Comment by MrZoidberg** [comment]
Sorry for a long delay. Totally forgot about this. It's now merged.
