### ISSUE TITLE
Add option to throw exception if configuration is not loaded

### ISSUE THREAD

**Issue by pseben** [MrZoidberg/VaultSharp.Extensions.Configuration#45]
Could we add similar feature as [.AddJsonFile()](https://learn.microsoft.com/cs-cz/dotnet/api/microsoft.extensions.configuration.jsonconfigurationextensions.addjsonfile?view=dotnet-plat-ext-7.0) optional parameter does ? It should allow throwing exception if credentials/token are invalid or there are some issues connecting to vault.

**Comment by MrZoidberg** [comment]
Fixed. Release will be soon.
