### ISSUE TITLE
Ability to set NoProxy on the HTTP client

### ISSUE THREAD

**Issue by deberhar** [MrZoidberg/VaultSharp.Extensions.Configuration#47]
### Ability to set NoProxy on the HTTP client

Good afternoon, would it be possible to expose a way to set `NoProxy=true` on the underlying HttpClient?  This would be helpful for working around proxy-configuration issues in our environment.

VaultSharp itself offers `PostProcessHttpClientHandlerAction` as a way to perform arbitrary configuration on the HttpClient.  One approach might be to expose access through a similar `Action<HttpClientHandler>?` property added to `VaultOptions`, which if set, could be invoked by VaultConfigurationProvider before the existing `AcceptInsecureConnections`-handling code.  This could then be leveraged by developers to adjust proxy settings (or make other HttpClient tweaks) as needed.

An alternative approach might be to more narrowly add support for a NoProxy option in `VaultOptions` and apply that explicitly in VaultConfigurationProvider's `PostProcessHttpClientHandlerAction` handler, if you'd prefer.

Happy to submit a PR for this; just let me know your preferred approach please.

**Comment by MrZoidberg** [comment]
Will take a look in nearest time. thanks

**Comment by MrZoidberg** [comment]
@deberhar I would like to implement the first approach, it looks reasonable. However, I'm struggling to write an integration test for it. Would you mind elaborating what are the preconditions when current version fails?
