### ISSUE TITLE
Could it be a good idea to add a try catch in the VaultChangeWatcher?

### ISSUE THREAD

**Issue by CodeLover254** [MrZoidberg/VaultSharp.Extensions.Configuration#56]
After using this package for a while, I have noticed the entire application stops whenever the VaultChangeWatcher background service encounters an exception. Mostly task cancelled exceptions due to http client timeout. I have the option of setting HostOptions.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.Ignore but that will not restart the VaultChangeWatcher afterwards. @MrZoidberg, any thoughts on this? Thinking of having a task delay in case of an exception after which the background service will continue running.

**Comment by MrZoidberg** [comment]
Hi, 

Thanks for your feedback. Yeah, it's worth changing. I'm a bit overloaded right now and will be able to work on this next week. But feel free to create a PR.

Thanks!

**Comment by CodeLover254** [comment]
Hello. No worries. I will work on the PR.
