### ISSUE TITLE
Support for JArray and non-string scalar types

### ISSUE THREAD

**Issue by almostjulian** [MrZoidberg/VaultSharp.Extensions.Configuration#7]
We've been considering using this library and migrating from appsettings.json..  Unfortunately, the current version doesn't handle JSON Arrays, nor does it handle values that aren't strings (in our case it was booleans, though I can certainly see some configs that have integers and the like).  I can help with a PR for this if need be.

**Comment by MrZoidberg** [comment]
@almostjulian thanks for your proposal. I will take a look at this issue on weekend

**Comment by MrZoidberg** [comment]
See https://github.com/MrZoidberg/VaultSharp.Extensions.Configuration/pull/11

**Comment by MrZoidberg** [comment]
@almostjulian fixed in 0.3.0
