### ISSUE TITLE
Option to omit Vault key name when generating config data

### ISSUE THREAD

**Issue by almostjulian** [MrZoidberg/VaultSharp.Extensions.Configuration#8]
We'd like an option to omit the Vault Key name in the generated Config... I get why it's the default, you need a unique identifier if you're looping through multiple keys, but in situations where you have a single key with a blob of nested JSON data, we'd rather not have the extra identifier.  Not sure if that's a corner case you'd be willing to support, but we would certainly appreciate it if you did.  Can help with a PR on this as well.

**Comment by MrZoidberg** [comment]
@almostjulian it's not a priority for me to have this feature, so it would be great if you can help with the PR. thanks!
